sonar.projectKey=BrunoIglina_Kata-Grupo7-stringCalculator
sonar.organization=brunoiglina

# Carpetas que Sonar debe analizar y reportar
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.test.js

# Ruta para que SonarCloud absorba la cobertura de tus Unit Tests
sonar.javascript.lcov.reportPaths=./coverage/lcov.info