name: Integracion Continua - Grupo 7 - Chiesa_Goya_Iglina_Montini

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Permisos necesarios para que la Action cree la web en GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga el código del repositorio
    - name: Checkout del código
      uses: actions/checkout@v4

    # 2. Configura Node.js versión 22
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    # 3. PASO 3 CI: Instalar dependencias de forma limpia (Garantiza compilación/integridad)
    - name: Instalar dependencias
      run: npm ci

    # 4. PASO 4 y 5 CI: Ejecuta los Unit Tests y genera la carpeta coverage/lcov-report/
    - name: Ejecutar Unit Tests y Cobertura
      run: npm test

    # 5. NUEVO PASO: Publica automáticamente la carpeta HTML en GitHub Pages
    - name: Desplegar Reporte HTML a GitHub Pages
      if: github.ref == 'refs/heads/main' # Solo se publica al impactar la rama main
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coverage/lcov-report